#!/usr/bin/env node
/**
 * Sync technology/**\/*.md into astro/src/content/docs/technology.
 *
 * Source of truth lives in /technology. This script copies markdown into
 * the Starlight content collection and rewrites Confluence-only syntax into
 * Starlight-friendly equivalents:
 *
 *   - Strips Confluence-mark HTML comments (<!-- Space: -->, <!-- Parent: -->,
 *     <!-- Macro: ... -->, <!-- Include: ... -->).
 *   - Converts :box:type:title:body: macros into Starlight admonitions.
 *   - Renames README.md -> index.md so each section gets a landing page.
 *   - Adds a frontmatter `title` (from the first H1) when missing.
 *   - Rewrites ![alt](path) to <img> so missing diagrams don't break the build.
 *   - Flattens single-page leaf directories: if a directory contains exactly
 *     one README.md and no markdown in any subdirectory, the README is moved
 *     up one level (e.g. deployment-view/README.md -> deployment-view.md). This
 *     keeps the sidebar from showing a useless `deployment-view` group around
 *     a single `Software Deployment View` page. Image references in those
 *     files are rewritten to keep resolving against their original location.
 *
 * Image directories alongside markdown are also copied so existing
 * `![alt](images/...)` references continue to resolve.
 */
import { promises as fs } from "node:fs";
import { existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, "../..");
const srcRoot = path.join(repoRoot, "technology");
const destRoot = path.join(
  repoRoot,
  "astro",
  "src",
  "content",
  "docs",
  "technology"
);

const CONFLUENCE_TYPE_TO_STARLIGHT = {
  info: "note",
  note: "note",
  warning: "caution",
  tip: "tip",
};

// Directories to exclude from sync. `output` holds generated PDFs/PNGs we
// don't want shipped with the site. `scratchpad` is informal working notes
// kept in the source repo for Confluence — out of scope for the public site.
const SKIP_DIRS = new Set(["output", "scratchpad"]);
const ASSET_EXTS = new Set([".png", ".jpg", ".jpeg", ".svg", ".gif", ".webp"]);

// Where to look for .c4 sources to extract LikeC4 view IDs from. Must match
// the `workspace` passed to LikeC4VitePlugin in astro.config.mjs.
const LIKEC4_WORKSPACE_REL = "current-state-views/structure-view";

// Component import metadata. `default` components live in this repo and need a
// path relative to the destination MDX file. `named` components live in an
// installed package and are imported by name.
const COMPONENT_IMPORTS = {
  LikeC4View: {
    kind: "default",
    path: path.resolve(
      fileURLToPath(import.meta.url),
      "../../src/components/LikeC4View.astro"
    ),
  },
  Tabs: { kind: "named", from: "@astrojs/starlight/components" },
  TabItem: { kind: "named", from: "@astrojs/starlight/components" },
  Badge: { kind: "named", from: "@astrojs/starlight/components" },
};

// Confluence `ac:status` colour → Starlight `<Badge variant>` mapping.
const STATUS_COLOUR_TO_VARIANT = {
  grey: "tip",
  blue: "note",
  yellow: "caution",
  green: "success",
  red: "danger",
};

// Sidebar ordering for autogenerated Starlight sections. Keyed by the source
// path under `technology/`, with `/README.md` or `.md` stripped. Lower
// numbers come first; pages without an entry fall through to Starlight's
// default alphabetical ordering. Lives here (not in source frontmatter) so the
// ordering is centralised and the source markdown stays Confluence-friendly.
const SIDEBAR_ORDER = {
  "current-state-views": 1,
  "current-state-views/structure-view": 2,
  "current-state-views/deployment-view": 3,
  "current-state-views/evolution-view": 4,
  "current-state-views/journey-view": 5,
  "quality-assurance-view": 2,
  "data-architecture": 3,
  "integration-architecture": 4,
  "integration-architecture/interfaces": 1,
  "integration-architecture/interfaces/example-partner-api": 2,
  "integration-architecture/interfaces/example-identity-provider": 3,
  "integration-architecture/interfaces/future-data-provider": 4,
};

function sidebarOrderFor(srcPath) {
  const rel = path.relative(srcRoot, srcPath).split(path.sep).join("/");
  const key = rel
    .replace(/\/README\.md$/i, "")
    .replace(/\.md$/i, "");
  return SIDEBAR_ORDER[key];
}

function stripConfluenceComments(md) {
  return md
    .replace(
      /<!--\s*(Space|Parent|Macro|Include|Layout|Title|Type|Label|Position|Title-Append):[\s\S]*?-->/g,
      ""
    )
    .replace(/^\s*\n+/, "");
}

function convertBoxMacros(md) {
  return md.replace(
    /^:box:([a-z]+):([^:]*):([\s\S]*?):\s*$/gm,
    (_match, type, title, body) => {
      const starlightType = CONFLUENCE_TYPE_TO_STARLIGHT[type] || "note";
      const head = title
        ? `:::${starlightType}[${title.trim()}]`
        : `:::${starlightType}`;
      return `${head}\n${body.trim()}\n:::`;
    }
  );
}

// Compute the site-rooted URL path (e.g. "/technology/foo/bar/") that
// Starlight will serve a given source markdown file at, taking flattening into
// account. Three cases:
//
//   - flattened: `parent/single.md` → /technology/.../parent/
//   - README.md: served at its containing directory's URL
//   - leaf .md:  served at /technology/.../<stem>/  (the file becomes
//                a URL-level directory with a trailing slash)
function destUrlPathFor(srcPath, flattenedSources) {
  const rel = path.relative(srcRoot, srcPath).split(path.sep).join("/");
  const base = path.basename(rel);
  const dir = path.dirname(rel);

  if (flattenedSources.has(srcPath)) {
    return `/technology/${dir}/`;
  }
  if (base.toLowerCase() === "readme.md") {
    return dir === "." ? `/technology/` : `/technology/${dir}/`;
  }
  const stem = base.replace(/\.md$/i, "");
  const dirPart = dir === "." ? "" : `${dir}/`;
  return `/technology/${dirPart}${stem}/`;
}

// Compute the browser-resolvable relative URL from one URL path to another.
// Both inputs are site-rooted, slash-terminated URL paths (as produced by
// destUrlPathFor). The output always has a trailing slash so it lands on
// Starlight's directory-style page URLs, and a leading `./` when needed so
// it's unambiguously relative.
function relativeUrlPath(fromUrl, toUrl) {
  const fromStripped = fromUrl.replace(/\/$/, "");
  const toStripped = toUrl.replace(/\/$/, "");
  let rel = path.posix.relative(fromStripped, toStripped);
  if (!rel) return "./";
  if (!rel.startsWith(".")) rel = `./${rel}`;
  return `${rel}/`;
}

// Rewrite markdown link targets that point at `.md` source files so they
// resolve to the correct Starlight URL. URL-aware (unlike a naive `.md → /`
// text rewrite), so it handles:
//
//   - non-README sources whose dest URL has an extra trailing-slash directory
//     level (Starlight serves `foo.md` at `/foo/`, off-by-one for relative
//     links anchored at the source file's URL)
//   - flattened targets whose dest URL collapses one path segment
//     (e.g. sda-adr-006/sda-adr-006.md → /technology/.../sda-adr-006/)
//
// Confluence-mark resolves the `.md` form against the source tree; this
// rewrite produces Astro-correct URLs in the synced copy so the same source
// link works in both targets. External URLs (`http(s)://…`), absolute paths
// (`/foo`), in-page anchors (`#section`) and image syntax (`![…](…)`) are
// left alone. Non-markdown relative links (e.g. `./foo.pdf`) are also left
// alone — they pass straight through Astro's static asset pipeline.
function rewriteMdLinks(md, srcPath, flattenedSources) {
  const fromUrl = destUrlPathFor(srcPath, flattenedSources);
  const srcDir = path.dirname(srcPath);
  return md.replace(
    /(?<!!)\[([^\]]*)\]\(([^)\s]+)(?:\s+"([^"]*)")?\)/g,
    (match, text, target, title) => {
      if (/^[a-z]+:/i.test(target) || target.startsWith("/") || target.startsWith("#")) {
        return match;
      }
      const [pathPart, anchor] = target.split("#", 2);
      if (!/\.md$/i.test(pathPart)) return match;
      const targetSrcPath = path.resolve(srcDir, pathPart);
      const toUrl = destUrlPathFor(targetSrcPath, flattenedSources);
      const rel = relativeUrlPath(fromUrl, toUrl);
      const newTarget = anchor ? `${rel}#${anchor}` : rel;
      const titlePart = title ? ` "${title}"` : "";
      return `[${text}](${newTarget}${titlePart})`;
    }
  );
}

// Convert inline `:status:Name:Colour:Subtle:` macros (Confluence `ac:status`)
// into Starlight `<Badge text="Name" variant="…" />` components. Colour maps
// to a Starlight variant; the `Subtle` flag is currently ignored (Starlight
// doesn't have a subtle variant). Returns the rewritten markdown plus the set
// of components that now need to be imported.
function convertStatusMacros(md) {
  const injected = new Set();
  const newMd = md.replace(
    /:status:([^:]+):([^:]+):(true|false):/g,
    (_match, name, colour) => {
      const variant =
        STATUS_COLOUR_TO_VARIANT[colour.trim().toLowerCase()] || "default";
      injected.add("Badge");
      const text = name.trim().replace(/"/g, "&quot;");
      return `<Badge text="${text}" variant="${variant}" />`;
    }
  );
  return { md: newMd, injected };
}

// Process ![alt](path) image references:
//   - External URLs and absolute paths: pass through unchanged.
//   - Relative paths to an image that exists on disk: keep markdown syntax
//     (so Astro's image pipeline optimizes and serves them) and apply the
//     flatten prefix so the path still resolves from the destination location.
//   - Relative paths to a missing image: replace with a visible placeholder
//     so the build doesn't fail on diagrams that haven't been generated yet.
//
//   `srcMdDir` — absolute path of the source markdown file's containing dir,
//                used to resolve relative image paths to filesystem locations.
//   `flattenPrefix` — directory name to prepend when this markdown was lifted
//                     one level up by the flattening pass (empty otherwise).
// Process ![alt](path) image references and decide what they become in the
// synced output:
//
//   1. External URLs / absolute paths: pass through unchanged.
//   2. LikeC4 view auto-detection: if the image's basename (filename minus
//      extension) matches a known LikeC4 view ID, swap the static-image
//      reference for an interactive `<LikeC4View viewId="..." />` tag. This
//      lets the same markdown serve both targets — Confluence renders the
//      static PNG (assuming `npm run export:structure-view` has been run),
//      while the Astro site renders the interactive view.
//   3. Existing relative path: keep markdown syntax (so Astro's image
//      pipeline optimizes and serves it) and apply the flatten prefix so
//      the path resolves from the destination location.
//   4. Missing relative path: replace with a visible placeholder so the
//      build never fails on diagrams that haven't been generated yet.
//
// Returns the rewritten markdown plus the set of component names that need
// to be imported at the top of the file (currently only LikeC4View).
function processImageReferences(md, srcMdDir, flattenPrefix, viewIds) {
  const injected = new Set();

  const newMd = md.replace(
    /!\[([^\]]*)\]\(([^)\s]+)(?:\s+"([^"]*)")?\)/g,
    (match, alt, src, _title) => {
      if (/^[a-z]+:/i.test(src) || src.startsWith("/")) return match;

      const filename = path.basename(src, path.extname(src));
      if (viewIds.has(filename)) {
        injected.add("LikeC4View");
        return `<LikeC4View viewId="${filename}" />`;
      }

      const absImagePath = path.resolve(srcMdDir, src);
      if (!existsSync(absImagePath)) {
        const escaped = src
          .replace(/&/g, "&amp;")
          .replace(/</g, "&lt;")
          .replace(/>/g, "&gt;");
        return `<span class="missing-diagram">📷 <em>Diagram pending:</em> <code>${escaped}</code></span>`;
      }

      const finalSrc = flattenPrefix ? `${flattenPrefix}${src}` : src;
      const titlePart = _title ? ` "${_title}"` : "";
      return `![${alt}](${finalSrc}${titlePart})`;
    }
  );

  return { md: newMd, injected };
}

// Convert `<!-- Tabs:start -->` / `<!-- Tabs:end -->` blocks into Starlight
// `<Tabs>` / `<TabItem>` markup. Each heading inside the block becomes a tab
// label; everything between consecutive headings becomes the tab body. The
// markers are HTML comments so they're invisible in Confluence — Confluence
// just sees the original headings and content, while Astro gets tabs.
//
// Runs *after* image processing so any LikeC4View auto-swap inside the block
// has already happened and ends up nested inside the right TabItem.
function processTabs(md) {
  const injected = new Set();
  const newMd = md.replace(
    /<!--\s*Tabs:start\s*-->([\s\S]*?)<!--\s*Tabs:end\s*-->/g,
    (_match, body) => {
      const lines = body.split("\n");
      const preamble = [];
      const sections = [];
      let current = null;
      for (const line of lines) {
        const heading = line.match(/^#{1,6}\s+(.+?)\s*$/);
        if (heading) {
          if (current) sections.push(current);
          current = { label: heading[1].trim(), content: [] };
        } else if (current) {
          current.content.push(line);
        } else {
          preamble.push(line);
        }
      }
      if (current) sections.push(current);
      if (sections.length === 0) return body;

      injected.add("Tabs");
      injected.add("TabItem");

      const items = sections
        .map((s) => {
          const label = s.label.replace(/"/g, "&quot;");
          const inner = s.content.join("\n").trim();
          return `  <TabItem label="${label}">\n\n${inner}\n\n  </TabItem>`;
        })
        .join("\n");
      const tabsBlock = `<Tabs>\n${items}\n</Tabs>`;
      const preambleText = preamble.join("\n").trim();
      return preambleText ? `${preambleText}\n\n${tabsBlock}` : tabsBlock;
    }
  );
  return { md: newMd, injected };
}

function ensureFrontmatter(md, fallbackTitle, sidebarOrder) {
  if (md.startsWith("---\n")) return md;
  const h1Match = md.match(/^#\s+(.+)$/m);
  const title = (h1Match ? h1Match[1] : fallbackTitle).trim();
  // Strip the source H1 once it's been promoted to the frontmatter title —
  // Starlight already renders the title as the page heading, so leaving the
  // H1 in the body produces a duplicate heading. The trailing blank line is
  // consumed too so the section that followed sits flush against the
  // frontmatter block in the synced output.
  const body = h1Match ? md.replace(/^#\s+.+\n(\n)?/m, "") : md;
  // When `sidebar.order` is set, also emit `sidebar.label` from the page
  // title. For an `index.md` inside an autogenerated directory, Starlight
  // uses sidebar.label to override the sub-group's directory-name label —
  // so an `interfaces/` directory whose index has `label: "Integration
  // Interfaces"` shows up as that in the sidebar instead of "interfaces".
  // For regular pages the explicit label matches the default behaviour, so
  // it's a harmless no-op.
  const sidebarBlock =
    sidebarOrder != null
      ? `\nsidebar:\n  order: ${sidebarOrder}\n  label: ${JSON.stringify(title)}`
      : "";
  return `---\ntitle: ${JSON.stringify(title)}${sidebarBlock}\n---\n\n${body}`;
}

function transform(md, fallbackTitle, srcPath, flattenedSources, flattenPrefix, viewIds, sidebarOrder) {
  const srcMdDir = path.dirname(srcPath);
  let out = stripConfluenceComments(md);
  out = convertBoxMacros(out);
  out = rewriteMdLinks(out, srcPath, flattenedSources);
  const { md: statusProcessed, injected: statusInjected } = convertStatusMacros(out);
  out = statusProcessed;
  const { md: imageProcessed, injected: imageInjected } = processImageReferences(
    out,
    srcMdDir,
    flattenPrefix,
    viewIds
  );
  out = imageProcessed;
  const { md: tabsProcessed, injected: tabsInjected } = processTabs(out);
  out = tabsProcessed;
  out = ensureFrontmatter(out, fallbackTitle, sidebarOrder);
  const injected = new Set([
    ...statusInjected,
    ...imageInjected,
    ...tabsInjected,
  ]);
  return { md: out, injected };
}

// Walk the LikeC4 workspace and collect every defined view ID. Matches
// `view <id>`, `view <id> of <element>`, `deployment view <id>` and
// `dynamic view <id>` declarations in any .c4 file.
async function collectLikeC4ViewIds(workspaceDir) {
  const ids = new Set();

  async function visit(dir) {
    let entries;
    try {
      entries = await fs.readdir(dir, { withFileTypes: true });
    } catch {
      return;
    }
    for (const entry of entries) {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        await visit(full);
      } else if (entry.name.endsWith(".c4")) {
        const content = await fs.readFile(full, "utf8");
        for (const m of content.matchAll(
          /^\s*(?:deployment|dynamic)?\s*view\s+([a-zA-Z_][\w]*)/gm
        )) {
          ids.add(m[1]);
        }
      }
    }
  }

  await visit(workspaceDir);
  return ids;
}

function relativeImportPath(fromFile, toAbsolute) {
  let rel = path.relative(path.dirname(fromFile), toAbsolute);
  if (!rel.startsWith(".") && !rel.startsWith("/")) rel = `./${rel}`;
  return rel.split(path.sep).join("/");
}

// Insert ESM imports for any Astro components we injected. Default-import
// components are local files (e.g. LikeC4View) imported via a relative path;
// named-import components live in installed packages (e.g. Starlight's Tabs)
// and get grouped into one import statement per source module.
// Imports go after the frontmatter block so MDX can resolve them.
function injectMdxImports(content, destPath, components) {
  const namedByModule = new Map();
  const defaultLines = [];
  for (const name of components) {
    const meta = COMPONENT_IMPORTS[name];
    if (!meta) {
      throw new Error(`No COMPONENT_IMPORTS entry for component "${name}"`);
    }
    if (meta.kind === "default") {
      defaultLines.push(
        `import ${name} from "${relativeImportPath(destPath, meta.path)}";`
      );
    } else {
      if (!namedByModule.has(meta.from)) namedByModule.set(meta.from, new Set());
      namedByModule.get(meta.from).add(name);
    }
  }
  const namedLines = [...namedByModule.entries()].map(
    ([from, names]) => `import { ${[...names].join(", ")} } from "${from}";`
  );
  const importLines = [...namedLines, ...defaultLines];

  const fmMatch = content.match(/^---\n[\s\S]*?\n---\n/);
  if (!fmMatch) {
    return `${importLines.join("\n")}\n\n${content}`;
  }
  const fm = fmMatch[0];
  const rest = content.slice(fm.length);
  return `${fm}\n${importLines.join("\n")}\n${rest}`;
}

async function readDirInfo(dir) {
  const entries = await fs.readdir(dir, { withFileTypes: true });
  const mdFiles = [];
  const subdirs = [];
  for (const entry of entries) {
    if (entry.isFile() && /\.md$/i.test(entry.name)) {
      mdFiles.push(entry.name);
    } else if (entry.isDirectory() && !SKIP_DIRS.has(entry.name)) {
      subdirs.push(entry.name);
    }
  }
  return { mdFiles, subdirs };
}

async function subtreeContainsMarkdown(dir) {
  const { mdFiles, subdirs } = await readDirInfo(dir);
  if (mdFiles.length > 0) return true;
  for (const sd of subdirs) {
    if (await subtreeContainsMarkdown(path.join(dir, sd))) return true;
  }
  return false;
}

// Walk the source tree and identify markdown files whose containing directory
// should be flattened away — the directory contains exactly one README.md and
// no markdown lives in any subdirectory below it. The root itself is never
// flattened.
async function planFlattening(rootDir) {
  const flattened = new Set();

  async function visit(dir, isRoot) {
    const { mdFiles, subdirs } = await readDirInfo(dir);

    let subdirHasMarkdown = false;
    for (const sd of subdirs) {
      const sdPath = path.join(dir, sd);
      if (await subtreeContainsMarkdown(sdPath)) subdirHasMarkdown = true;
      await visit(sdPath, false);
    }

    // Flatten any directory whose only markdown is a single file with no
    // markdown deeper in the tree. The destination name becomes
    // <dirname>.md regardless of the source filename, so e.g.
    // sda-adr-006/sda-adr-006.md -> sda-adr-006.md and
    // deployment-view/README.md -> deployment-view.md.
    if (!isRoot && mdFiles.length === 1 && !subdirHasMarkdown) {
      flattened.add(path.join(dir, mdFiles[0]));
    }
  }

  await visit(rootDir, true);
  return flattened;
}

async function walk(dir, results = []) {
  const entries = await fs.readdir(dir, { withFileTypes: true });
  for (const entry of entries) {
    if (entry.isDirectory() && SKIP_DIRS.has(entry.name)) continue;
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      await walk(full, results);
    } else {
      results.push(full);
    }
  }
  return results;
}

function destForMarkdown(srcPath, flattenedSources) {
  const rel = path.relative(srcRoot, srcPath);
  if (flattenedSources.has(srcPath)) {
    // <parent-dir>/<README.md> -> <parent-dir>.md (one level up)
    const dir = path.dirname(rel);
    return path.join(destRoot, `${dir}.md`);
  }
  const dir = path.dirname(rel);
  const base = path.basename(rel);
  const renamed = base.toLowerCase() === "readme.md" ? "index.md" : base;
  return path.join(destRoot, dir, renamed);
}

// Switch a destination path's extension from .md to .mdx. Used when a file
// has injected Astro components (e.g. <LikeC4View>) and needs MDX parsing.
function toMdxPath(p) {
  return p.replace(/\.md$/i, ".mdx");
}

// MDX rejects HTML comments — `<!-- ... -->` becomes a parser error. The
// source markdown often contains Marp directives or Confluence notes inside
// HTML comments; convert them to MDX comment expressions `{/* ... */}` so
// they remain in the output but stop breaking the build.
function htmlCommentsToMdx(md) {
  return md.replace(/<!--([\s\S]*?)-->/g, (_m, body) => {
    // MDX expression comments can't contain `*/`; escape any that appear.
    const safe = body.replace(/\*\//g, "*\\/");
    return `{/*${safe}*/}`;
  });
}

function destForAsset(srcPath) {
  return path.join(destRoot, path.relative(srcRoot, srcPath));
}

async function copyAsset(srcPath) {
  const dest = destForAsset(srcPath);
  await fs.mkdir(path.dirname(dest), { recursive: true });
  await fs.copyFile(srcPath, dest);
}

async function processMarkdown(srcPath, flattenedSources, viewIds) {
  const raw = await fs.readFile(srcPath, "utf8");
  const isFlattened = flattenedSources.has(srcPath);
  const srcMdDir = path.dirname(srcPath);
  const containingDirName = path.basename(srcMdDir);
  const fallbackTitle = isFlattened
    ? containingDirName
    : path.basename(srcPath, path.extname(srcPath));
  const flattenPrefix = isFlattened ? `${containingDirName}/` : "";
  const sidebarOrder = sidebarOrderFor(srcPath);
  const { md, injected } = transform(
    raw,
    fallbackTitle,
    srcPath,
    flattenedSources,
    flattenPrefix,
    viewIds,
    sidebarOrder
  );
  // If we injected any Astro components, the file must be MDX — and MDX
  // rejects HTML comments, so convert them before adding the import block.
  const isMdx = injected.size > 0;
  const dest = isMdx
    ? toMdxPath(destForMarkdown(srcPath, flattenedSources))
    : destForMarkdown(srcPath, flattenedSources);
  const final = isMdx
    ? injectMdxImports(htmlCommentsToMdx(md), dest, injected)
    : md;
  await fs.mkdir(path.dirname(dest), { recursive: true });
  await fs.writeFile(dest, final, "utf8");
  return { injectedCount: injected.size };
}

async function main() {
  await fs.rm(destRoot, { recursive: true, force: true });
  await fs.mkdir(destRoot, { recursive: true });

  const flattenedSources = await planFlattening(srcRoot);
  const viewIds = await collectLikeC4ViewIds(
    path.join(srcRoot, LIKEC4_WORKSPACE_REL)
  );

  const files = await walk(srcRoot);
  let mdCount = 0;
  let assetCount = 0;
  let likec4InjectedFiles = 0;
  for (const file of files) {
    const ext = path.extname(file).toLowerCase();
    if (ext === ".md") {
      const { injectedCount } = await processMarkdown(
        file,
        flattenedSources,
        viewIds
      );
      mdCount += 1;
      if (injectedCount > 0) likec4InjectedFiles += 1;
    } else if (ASSET_EXTS.has(ext)) {
      await copyAsset(file);
      assetCount += 1;
    }
  }

  console.log(
    `Synced ${mdCount} markdown file(s) and ${assetCount} image(s) → ${path.relative(
      repoRoot,
      destRoot
    )} (flattened ${flattenedSources.size} single-page director${flattenedSources.size === 1 ? "y" : "ies"}, ${viewIds.size} LikeC4 view ID(s) detected, ${likec4InjectedFiles} file(s) upgraded to interactive views)`
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
