// @ts-check
import { defineConfig } from "astro/config";
import starlight from "@astrojs/starlight";
import react from "@astrojs/react";
import { LikeC4VitePlugin } from "likec4/vite-plugin";
import remarkMermaid from "./src/lib/remark-mermaid.mjs";

// Client-side mermaid renderer. mermaid.js finds <pre class="mermaid">
// elements (produced by the remark plugin) and replaces them with SVG.
// Loaded from a CDN to avoid bundling mermaid into every page.
const mermaidInitScript = `
  import mermaid from "https://esm.sh/mermaid@11";
  mermaid.initialize({ startOnLoad: false, theme: "default", securityLevel: "loose" });
  const run = () => mermaid.run({ querySelector: ".mermaid" });
  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", run);
  } else {
    run();
  }
`;

// Deployment URL configuration.
// PAGES_SITE_URL is the full public URL (e.g. https://defra.github.io/cattle-vaccination-documentation/).
// Extract its pathname as the base so asset paths are root-relative to the
// correct sub-path, rather than hardcoding "/" which breaks sub-directory deploys.
const pagesUrl = process.env.PAGES_SITE_URL;
const basePath = pagesUrl
  ? new URL(pagesUrl).pathname
  : process.env.BASE_PATH || "/cattle-vaccination-docs/";

export default defineConfig({
  site: pagesUrl || `https://defra.github.io${process.env.BASE_PATH || "/cattle-vaccination-docs"}`,

  base: basePath,

  markdown: {
    remarkPlugins: [remarkMermaid],
  },

  vite: {
    plugins: [
      LikeC4VitePlugin({
        // Read .c4 sources directly from the technology current-state-views structure view.
        workspace: "../technology/current-state-views/structure-view",
      }),
      // Astro's dev server doesn't resolve directory indexes for files in
      // `public/`, so a request to /likec4/ 404s even though /likec4/index.html
      // exists. Production servers (astro preview, GitHub Pages) do resolve it,
      // so this middleware is dev-only to make the two environments match.
      {
        name: "likec4-dev-index-fallback",
        configureServer(server) {
          server.middlewares.use((req, _res, next) => {
            if (req.url && /\/likec4\/(\?.*)?$/.test(req.url)) {
              req.url = req.url.replace(/\/likec4\//, "/likec4/index.html");
            }
            next();
          });
        },
      },
    ],
  },

  integrations: [
    react({
      include: ["**/react/*", "**/components/**"],
      experimentalReactChildren: true,
    }),
    starlight({
      title: "Cattle Vaccination",
      head: [
        {
          tag: "script",
          attrs: { type: "module" },
          content: mermaidInitScript,
        },
      ],
      // Sidebar mirrors the Confluence "Technology" hierarchy
      // (one section per top-level area). Pages are auto-generated from
      // the synced directory tree under src/content/docs/technology.
      sidebar: [
        {
          label: "Technology",
          link: "/technology/",
        },
        {
          label: "Current State Views",
          collapsed: false,
          // Starlight v0.39 removed autogenerated sidebar *groups*: an
          // autogenerate config must now live inside a group's `items` array
          // rather than on the group itself.
          items: [
            {
              autogenerate: {
                directory: "technology/current-state-views",
                collapsed: false,
              },
            },
          ],
        },
        {
          label: "Data Architecture",
          collapsed: false,
          items: [
            {
              autogenerate: {
                directory: "technology/data-architecture",
                collapsed: false,
              },
            },
          ],
        },
        // Integration Architecture is configured manually because autogenerate
        // can't customise an inner sub-group's label (it uses the directory
        // name, e.g. "interfaces" lowercase) or position it via the index.md's
        // sidebar frontmatter. Top-level order is: index → patterns → the
        // Interfaces sub-group (which itself autogenerates from its three
        // example pages, picked up in maturity order via SIDEBAR_ORDER).
        {
          label: "Integration Architecture",
          collapsed: false,
          items: [
            {
              label: "Integration Architecture",
              link: "/technology/integration-architecture/",
            },
            {
              label: "Integration Patterns",
              link: "/technology/integration-architecture/patterns/",
            },
            {
              label: "Integration Interfaces",
              collapsed: false,
              items: [
                {
                  autogenerate: {
                    directory:
                      "technology/integration-architecture/interfaces",
                    collapsed: false,
                  },
                },
              ],
            },
          ],
        },
        {
          label: "Quality Assurance",
          collapsed: false,
          items: [
            {
              autogenerate: {
                directory: "technology/quality-assurance-view",
                collapsed: false,
              },
            },
          ],
        },
        {
          label: "Architecture Diagrams",
          link: "/likec4/",
          attrs: { target: "_blank", rel: "noopener" },
        },
      ],
    }),
  ],
});
